spring:
  application:
    name: blog-user
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:cache.yml,classpath:rpc.yml

server:
  port: 8083

dubbo:
  provider:
    filter: -exception
#dubbo:
#  protocol:
#    port: 20889
#  application:
#    qos-port: 33333
